# Generated by Django 3.2.12 on 2022-04-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20220329_2101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country', 'state')},
        ),
    ]
