# Generated by Django 3.2.12 on 2022-04-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('name', 'user')},
        ),
    ]
